# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'



variables:
  buildConfiguration: 'Release'

# do this before your build tasks

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 3.0.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Install dotnetsay'
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g dotnetsay'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'pipelines-dotnet-core.csproj'
    arguments: '--configuration Release' # Update this to match your need

#- task: DotNetCoreCLI@2
#  inputs:
#    command: restore
#   projects: 'pipelines-dotnet-core.csproj'
#  feedsToUse: config
#   nugetConfigPath: NuGet.config    # Relative to root of the repository
#  externalFeedCredentials: <Name of the NuGet service connection>

#- script: dotnet build --configuration $(buildConfiguration)
 #  displayName: 'dotnet build $(buildConfiguration)'

# ...